version: 2

updates:
  - package-ecosystem: "NuGet"
    directory: "/src"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
